name: Deploy Local POC

on:
  workflow_run:
    workflows: ["CI Pipeline"]   # must exactly match ci.yml name
    types:
      - completed

jobs:
  deploy-local:
    runs-on: ubuntu-latest
    env:
      repo: ${{ github.repository }}
      sha: ${{ github.event.workflow_run.head_sha }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run Docker container locally
        run: |
          echo: "Inspecting image contents"
          docker run --rm "ghcr.io/${repo,,}/cicd-demo:${sha::7}" ls -1 /app

        
          echo "Running image ghcr.io/${repo,,}/cicd-demo:${sha::7}"

          docker rm -f cicd-demo || true
          docker run -d --name cicd-demo -p 8080:80 "ghcr.io/${repo,,}/cicd-demo:${sha::7}"
          
          echo "=== Deployment info ==="
          docker ps -a
          docker images | grep cicd-demo

          echo "=== Container logs ==="
          docker logs cicd-demo
